version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: cinequest_db
    environment:
      POSTGRES_USER: cinequest
      POSTGRES_PASSWORD: p#ssword3
      POSTGRES_DB: cinequest_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: